services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres_user -d postgres_database']
      interval: 5s
      retries: 5
      timeout: 3s

  express-dev-app:
    volumes:
      - .:/usr/src/app
    build:
      dockerfile: ./express-dev-app.dockerfile
    ports:
      - '5001:5001'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  db-seeder:
    image: node:20
    container_name: db_seeder
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "db:init"]
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  dev-frontend:
    volumes:
      - .:/usr/src/app
    build:
      dockerfile: ./vite-dev-frontend.dockerfile
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env


volumes:
  postgres_data:
    external: false
