services:
  postgres_db:
    image: postgres:15
    hostname: postgres_host
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres_database
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  express-dev-server:
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: express-dev-server.dockerfile
    ports:
      - '5001:5001'
    stdin_open: true
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - prisma-network

volumes:
  postgres_data:
    external: false

networks:
  prisma-network:
    name: prisma-network
